---
:input_file: ./data/nh/2026_2027_AgencyBudget.csv
:header_row: 5
:data_row: 6
:period: '2026'
:name:   'NH Agency'
:header_levels: [ 'Fund', 'Category of Government', 'Department', 'Agency', 'Activity', 'Class']
:header_expense_or_fund : 'Record Type'
:header_dollars : 'FY27 Total Request'
